# Generated by Django 6.0.3 on 2026-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_coupon_order_coupon_code_order_discount_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
