# Generated by Django 6.0.7 on 2026-08-19 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_gift_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcardusage",
            name="gift_card",
        ),
        migrations.RemoveField(
            model_name="giftcardusage",
            name="order",
        ),
        migrations.DeleteModel(
            name="GiftCard",
        ),
        migrations.DeleteModel(
            name="GiftCardUsage",
        ),
    ]
