# Generated by Django 6.0.7 on 2026-08-19 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_remove_giftcardusage_gift_card_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=16, unique=True, verbose_name="Mã thẻ"
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Giá trị ban đầu"
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="Số dư hiện tại",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="VND", max_length=3, verbose_name="Đơn vị tiền tệ"
                    ),
                ),
                (
                    "purchaser_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email người mua"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email người nhận"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Tên người nhận"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Lời nhắn")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang hoạt động"),
                            ("redeemed", "Đã dùng hết"),
                            ("expired", "Hết hạn"),
                            ("cancelled", "Đã hủy"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Hạn sử dụng")),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "purchaser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_cards_purchased",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người mua",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thẻ quà tặng",
                "verbose_name_plural": "Thẻ quà tặng",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftCardUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Số tiền đã dùng"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Số dư còn lại"
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gift_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="orders.giftcard",
                        verbose_name="Thẻ quà tặng",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_card_usages",
                        to="orders.order",
                        verbose_name="Đơn hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử sử dụng thẻ",
                "verbose_name_plural": "Lịch sử sử dụng thẻ",
                "ordering": ["-used_at"],
            },
        ),
    ]
