# Generated by Django 5.2.16 on 2026-09-17 18:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_alter_couponredemption_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refunded_amount",
            field=models.DecimalField(
                decimal_places=0, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vnpay_transaction_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refund_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="stock_restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("approved", "Đã duyệt"),
                    ("received", "Đã nhận và kiểm tra hàng"),
                    ("rejected", "Từ chối"),
                    ("refunded", "Đã hoàn tiền"),
                    ("exchanged", "Đã đổi hàng"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RefundRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=32, unique=True)),
                ("transaction_id", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang xác nhận"),
                            ("succeeded", "Đã hoàn qua cổng"),
                            ("failed", "Cổng từ chối"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("gateway_code", models.CharField(blank=True, max_length=20)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="orders.order",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "status"],
                        name="orders_refu_order_i_bacf9d_idx",
                    )
                ],
            },
        ),
    ]
