# Generated by Django 5.2.16 on 2026-09-17 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0019_order_delivered_at_order_refunded_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("processing", "Đang xử lý"),
                            ("shipping", "Đang giao"),
                            ("delivered", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="system", max_length=32)),
                ("transaction_id", models.CharField(blank=True, max_length=64)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử trạng thái đơn hàng",
                "verbose_name_plural": "Lịch sử trạng thái đơn hàng",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["order", "created_at"],
                        name="orders_orde_order_i_1de1d7_idx",
                    )
                ],
            },
        ),
    ]
