# Generated by Django 5.2.16 on 2026-09-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0021_protect_order_item_products_and_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="stackable",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Tắt = mã độc quyền, không cộng với giảm giá hạng và điểm.",
                verbose_name="Được cộng dồn",
            ),
        ),
    ]
