# Generated by Django 5.2.17 on 2026-09-26 19:31

from django.db import migrations, models


def backfill_product_name(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    for item in OrderItem.objects.filter(product_name="").select_related("product"):
        if item.product_id and item.product:
            OrderItem.objects.filter(id=item.id).update(
                product_name=item.product.name[:255]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_coupon_stackable'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(
            backfill_product_name, migrations.RunPython.noop
        ),
    ]
