# Generated by OpenAI Codex on 2026-05-14

from django.db import migrations, models


def seed_support_faq(apps, schema_editor):
    SupportFAQ = apps.get_model("products", "SupportFAQ")
    items = [
        {
            "question": "Phi ship the nao?",
            "keywords": "ship,giao,van chuyen,phi ship,free ship",
            "answer": "Shop free ship toan quoc cho don tu 499K. Ban co the them san pham vao gio de xem phi ship truoc khi dat hang.",
            "priority": 10,
        },
        {
            "question": "Co thanh toan chuyen khoan khong?",
            "keywords": "thanh toan,chuyen khoan,cod,ngan hang",
            "answer": "Shop ho tro thanh toan khi nhan hang va chuyen khoan ngan hang. O trang checkout ban co the chon phuong thuc phu hop.",
            "priority": 20,
        },
        {
            "question": "Lam sao theo doi don?",
            "keywords": "don,theo doi,trang thai,ma don",
            "answer": "Neu da dang nhap, ban vao muc Don hang de xem trang thai. Sau khi dat thanh cong, he thong cung hien trang xac nhan don ngay tren web.",
            "priority": 30,
        },
        {
            "question": "Tu van size",
            "keywords": "size,kich co,rong,chat lieu,form",
            "answer": "Ban nen vao trang chi tiet san pham de chon mau va size. Neu can, hay gui them chieu cao, can nang va form mac mong muon de shop tu van nhanh hon.",
            "priority": 40,
        },
        {
            "question": "Doi tra nhu the nao?",
            "keywords": "doi,tra,hoan,huy",
            "answer": "Ban hay lien he shop som nhat sau khi nhan hang neu can doi tra. Shop se can ma don, san pham va ly do doi tra de ho tro nhanh.",
            "priority": 50,
        },
    ]

    for item in items:
        SupportFAQ.objects.get_or_create(question=item["question"], defaults=item)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_wishlistitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlistitem",
            options={
                "ordering": ["-created"],
                "verbose_name": "Sản phẩm yêu thích",
                "verbose_name_plural": "Sản phẩm yêu thích",
            },
        ),
        migrations.CreateModel(
            name="SupportFAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255, verbose_name="Câu hỏi")),
                ("keywords", models.CharField(blank=True, max_length=255, verbose_name="Từ khóa")),
                ("answer", models.TextField(verbose_name="Câu trả lời")),
                ("priority", models.PositiveSmallIntegerField(default=100, verbose_name="Độ ưu tiên")),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang dùng")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ hỗ trợ",
                "verbose_name_plural": "FAQ hỗ trợ",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="supportfaq",
            index=models.Index(fields=["is_active", "priority"], name="products_su_is_acti_1d2b34_idx"),
        ),
        migrations.AddIndex(
            model_name="supportfaq",
            index=models.Index(fields=["question"], name="products_su_questio_05f0da_idx"),
        ),
        migrations.RunPython(seed_support_faq, migrations.RunPython.noop),
    ]
