# Generated by OpenAI Codex on 2026-05-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_supportfaq_and_alter_wishlistitem_options"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="supportfaq",
            new_name="products_su_is_acti_7e0beb_idx",
            old_name="products_su_is_acti_1d2b34_idx",
        ),
        migrations.RenameIndex(
            model_name="supportfaq",
            new_name="products_su_questio_a0a8aa_idx",
            old_name="products_su_questio_05f0da_idx",
        ),
    ]
