# Generated by Django 6.0.3 on 2026-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
