# Generated by Django 6.0.3 on 2026-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Đang bán'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Nổi bật'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=10, verbose_name='Giá tiền'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Màu sắc'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Size'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'featured', 'price'], name='products_pr_availab_7bbb0d_idx'),
        ),
    ]
