# Generated by Django 6.0.7 on 2026-08-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_review_shop_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer_reply',
            field=models.TextField(blank=True, verbose_name='Khách hàng phản hồi shop'),
        ),
    ]
