# Generated by Django 6.0.7 on 2026-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_review_customer_reply"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)), name="product_stock_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)),
                name="productvariant_stock_non_negative",
            ),
        ),
    ]
