# Generated by Django 5.2.16 on 2026-09-19 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_add_upload_validation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("new_price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("changed_by", models.CharField(blank=True, max_length=150)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử giá",
                "verbose_name_plural": "Lịch sử giá",
                "ordering": ["-changed_at"],
            },
        ),
    ]
