CATEGORY_SLUG_AO = "ao"
CATEGORY_SLUG_QUAN = "quan"
CATEGORY_SLUG_PHU_KIEN = "phu-kien"

APPAREL_CATEGORY_SLUGS = {CATEGORY_SLUG_AO, CATEGORY_SLUG_QUAN}

CATEGORY_TYPE_LABELS = {
    CATEGORY_SLUG_AO: "ÁO",
    CATEGORY_SLUG_QUAN: "QUẦN",
    CATEGORY_SLUG_PHU_KIEN: "PHỤ KIỆN",
}

DEFAULT_CATEGORY_TYPE_LABEL = "SẢN PHẨM"
FEATURED_PRODUCT_LIMIT = 12


def get_category_type_label(category_slug):
    return CATEGORY_TYPE_LABELS.get(category_slug, DEFAULT_CATEGORY_TYPE_LABEL)
