# Generated by Django 6.0.7 on 2026-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Điểm tích lũy"
            ),
        ),
    ]
