# Generated by Django 5.2.17 on 2026-09-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_useraddress_is_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='SĐT đã xác minh'),
        ),
    ]
